### ISSUE TITLE
Where can i find the uncompiled version

### ISSUE THREAD

**Issue by TechGeekUnited** [Brandon421-ops/Bunker-v6-Proxy-And-Browser#1]
I love the page and stuff but i can't find the source code for compiled.js to customize it; where can i find the source code?

**Comment by Brandon421-ops** [comment]
well heres the problem idk where to find the uncompiled version because i didn't make it someone else did

**Comment by TechGeekUnited** [comment]
Nevermind i figured it out by reading through compiled.js Until i found the code for the badly made compiler that compiled itself into cocompiled.js and just made a simple decompiler.(https://github.com/TechGeekUnited/bunker/blob/master/decompiler.js/https://github.com/TechGeekUnited/bunker/tree/master/decompiled)
